name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # Esto es cada día a las 00:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 🛎️
        uses: actions/checkout@v3

      - name: Generate Snake SVG 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: JoannMr
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg

      - name: Commit and Push 🚀
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "🐍 Generate GitHub Snake contribution graph"
          add: "output/*.svg"
